import { AWSResource } from '@/types/aws';

function collectResourceTypes(resources: AWSResource[]): Set<string> {
  const types = new Set<string>();

  function traverse(resource: AWSResource) {
    if (resource.type !== 'Infrastructure') {
      types.add(resource.type);
    }
    if (resource.children) {
      resource.children.forEach(traverse);
    }
  }

  resources.forEach(traverse);
  return types;
}

function countResourcesByType(resources: AWSResource[]): Map<string, number> {
  const counts = new Map<string, number>();

  function traverse(resource: AWSResource) {
    if (resource.type !== 'Infrastructure') {
      counts.set(resource.type, (counts.get(resource.type) || 0) + 1);
    }
    if (resource.children) {
      resource.children.forEach(traverse);
    }
  }

  resources.forEach(traverse);
  return counts;
}

export function generateReadme(resources: AWSResource[], region: string): string {
  const resourceTypes = collectResourceTypes(resources);
  const resourceCounts = countResourcesByType(resources);

  const resourceList = Array.from(resourceCounts.entries())
    .map(([type, count]) => `- **${type}**: ${count}`)
    .join('\n');

  const modulesList = Array.from(resourceTypes)
    .filter(t => t !== 'Infrastructure')
    .map(t => `- \`modules/${t.toLowerCase()}/\` - ${t} module`)
    .join('\n');

  return `# Terraform Infrastructure

Generated by [React2AWS](https://react2aws.xyz)

## Directory Structure

\`\`\`
.
├── main.tf                     # Provider and module configuration
├── variables.tf                # Input variables
├── outputs.tf                  # Output values
├── backend.tf                  # Remote state configuration (optional)
├── terraform.tfvars            # Variable values
├── modules/                    # Reusable Terraform modules
${Array.from(resourceTypes).filter(t => t !== 'Infrastructure').map(t => `│   └── ${t.toLowerCase()}/`).join('\n')}
└── README.md
\`\`\`

## Resources

${resourceList}

## Modules

${modulesList}

## Quick Start

### Prerequisites

- [Terraform](https://www.terraform.io/downloads.html) >= 1.0
- [AWS CLI](https://aws.amazon.com/cli/) configured with appropriate credentials
- An AWS account with appropriate permissions

### 1. Configure Variables

Update \`terraform.tfvars\` with your values:

\`\`\`hcl
project_name = "myapp"
environment  = "development"  # or "staging", "production"
\`\`\`

### 2. Deploy

\`\`\`bash
# Initialize Terraform
terraform init

# Review the plan
terraform plan

# Apply the changes
terraform apply
\`\`\`

### 3. Environment-Specific Deployments

For different environments, use Terraform workspaces:

\`\`\`bash
# Create and switch to production workspace
terraform workspace new prod
terraform workspace select prod

# Update terraform.tfvars
environment = "production"

# Deploy
terraform apply
\`\`\`

Or use separate \`.tfvars\` files:

\`\`\`bash
terraform apply -var-file="prod.tfvars"
\`\`\`

## Environment Settings

The \`environment\` variable controls production-grade features:

| Setting | development/staging | production |
|---------|---------------------|------------|
| Instance sizes | Cost-optimized | Production-ready |
| Multi-AZ | No | Yes |
| Deletion protection | No | Yes |
| Backup retention | Minimal | 7+ days |
| NAT Gateway | Single | Per-AZ |
| Auto-scaling | Disabled | Enabled |
| Enhanced monitoring | No | Yes |

Set \`environment = "production"\` in \`terraform.tfvars\` to enable production settings.

## Remote State (Optional)

For team collaboration, configure remote state in \`backend.tf\`:

\`\`\`bash
# Create S3 bucket for state storage
aws s3 mb s3://YOUR_PROJECT_NAME-terraform-state --region ${region}

# Create DynamoDB table for state locking
aws dynamodb create-table \\
  --table-name YOUR_PROJECT_NAME-terraform-locks \\
  --attribute-definitions AttributeName=LockID,AttributeType=S \\
  --key-schema AttributeName=LockID,KeyType=HASH \\
  --billing-mode PAY_PER_REQUEST \\
  --region ${region}
\`\`\`

Then uncomment the backend configuration in \`backend.tf\`.

## Module Documentation

### VPC Module

Creates a VPC with public and private subnets across 3 availability zones.

**Inputs:**
- \`name\` - VPC identifier
- \`cidr\` - VPC CIDR block (default: 10.0.0.0/16)
- \`enable_nat_gateway\` - Enable NAT for private subnets
- \`single_nat_gateway\` - Use single NAT (cost saving)

**Outputs:**
- \`vpc_id\` - VPC ID
- \`private_subnet_ids\` - Private subnet IDs
- \`public_subnet_ids\` - Public subnet IDs

### Lambda Module

Creates a Lambda function with IAM role and optional VPC configuration.

**Inputs:**
- \`name\` - Function name
- \`runtime\` - Lambda runtime (default: nodejs20.x)
- \`vpc_config\` - VPC configuration (optional)
- \`s3_bucket_arns\` - S3 buckets to grant access
- \`dynamodb_table_arns\` - DynamoDB tables to grant access

**Outputs:**
- \`function_arn\` - Lambda ARN
- \`function_url\` - Function URL (if enabled)

## Cleanup

To destroy resources:

\`\`\`bash
terraform destroy
\`\`\`

**Note:** If \`environment = "production"\`, deletion protection is enabled. You must first:
1. Set \`environment = "development"\` in \`terraform.tfvars\`
2. Run \`terraform apply\`
3. Then run \`terraform destroy\`

## Support

- [React2AWS GitHub](https://github.com/mmarinovic/React2AWS)
- [Terraform AWS Provider Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)
`;
}
